# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distn <- function(X, n) {
    .Call(`_RobustSpline_distn`, X, n)
}

distnAB <- function(A, B, m, n) {
    .Call(`_RobustSpline_distnAB`, A, B, m, n)
}

solveC <- function(A, B) {
    .Call(`_RobustSpline_solveC`, A, B)
}

psiwC <- function(t, type, alpha, tuning) {
    .Call(`_RobustSpline_psiwC`, t, type, alpha, tuning)
}

IRLSC <- function(Z, Y, lambda, H, type, alpha, W, sc, residsin, tuning, toler, imax) {
    .Call(`_RobustSpline_IRLSC`, Z, Y, lambda, H, type, alpha, W, sc, residsin, tuning, toler, imax)
}

IRLSCmult <- function(Z, Y, lambda, H, type, alpha, W, sc, tuning, toler, imax) {
    .Call(`_RobustSpline_IRLSCmult`, Z, Y, lambda, H, type, alpha, W, sc, tuning, toler, imax)
}

ridgeC <- function(Z, Y, lambda, H, W) {
    .Call(`_RobustSpline_ridgeC`, Z, Y, lambda, H, W)
}

HuberQpC <- function(Z, Y, H, w, delta = 1.345, eps_abs = 1e-6, eps_rel = 1e-6) {
    .Call(`_RobustSpline_HuberQpC`, Z, Y, H, w, delta, eps_abs, eps_rel)
}

QuantileQpC <- function(Z, Y, lambda, H, w, alpha = 0.5, eps_abs = 1e-6, eps_rel = 1e-6) {
    .Call(`_RobustSpline_QuantileQpC`, Z, Y, lambda, H, w, alpha, eps_abs, eps_rel)
}

