# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distn <- function(X, n, d) {
    .Call(`_RobustSpline_distn`, X, n, d)
}

distnAB <- function(A, B, m, n, d) {
    .Call(`_RobustSpline_distnAB`, A, B, m, n, d)
}

solveC <- function(A, B) {
    .Call(`_RobustSpline_solveC`, A, B)
}

psiwC <- function(t, type, tuning) {
    .Call(`_RobustSpline_psiwC`, t, type, tuning)
}

IRLSC <- function(Z, Y, lambda, H, type, sc, residsin, tuning, toler, imax) {
    .Call(`_RobustSpline_IRLSC`, Z, Y, lambda, H, type, sc, residsin, tuning, toler, imax)
}

ridgeC <- function(Z, Y, lambda, H) {
    .Call(`_RobustSpline_ridgeC`, Z, Y, lambda, H)
}

